# Generated by Django 4.0.6 on 2022-08-27 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip2location', '0002_alter_history_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
